# Generated by Django 6.0.3 on 2026-04-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="full_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Полное описание"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Краткое описание"
            ),
        ),
    ]
