# Generated by Django 6.0.3 on 2026-04-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_service_full_description_alter_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
