# Generated by Django 6.0.3 on 2026-04-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_service_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactinfo",
            options={"verbose_name": "Контакты", "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name": "Доктор", "verbose_name_plural": "Доктора"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Услуга", "verbose_name_plural": "Услуги"},
        ),
    ]
