# Generated by Django 6.0.3 on 2026-04-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
            },
        ),
    ]
